version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: chicago_311_mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      # Disabled authentication for development
      # MONGO_INITDB_ROOT_USERNAME: admin
      # MONGO_INITDB_ROOT_PASSWORD: chicago311pass
      MONGO_INITDB_DATABASE: chicago_311
    volumes:
      - mongodb_data:/data/db
      - ./scripts/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - chicago_311_network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.2
    container_name: chicago_311_elasticsearch
    restart: unless-stopped
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
      - cluster.name=chicago-311-cluster
      - node.name=chicago-311-node
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - chicago_311_network
    ulimits:
      memlock:
        soft: -1
        hard: -1

  kibana:
    image: docker.elastic.co/kibana/kibana:8.8.2
    container_name: chicago_311_kibana
    restart: unless-stopped
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
      ELASTICSEARCH_URL: http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - chicago_311_network

volumes:
  mongodb_data:
    driver: local
  elasticsearch_data:
    driver: local

networks:
  chicago_311_network:
    driver: bridge